apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rideshare-drivers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rideshare-drivers
    spec:
      containers:
      - name: rideshare-drivers
        image: khaledhikmat/rideshare-drivers:v1
        ports:
        - containerPort: 80
        env:
        - "name": "APPINSIGHTS_INSTRUMENTATIONKEY"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "FUNCTIONS_EXTENSION_VERSION"
          "value": "2.0.11961-alpha"
        - "name": "AzureWebJobsDashboard"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "AzureWebJobsStorage"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "DocDbApiKey"
          "value": "QGwfwS1QQDgfmiE7PFwZoAZwtwdB3yzZT3A5LgeXe0Go4WRqYbnXurlcHbOUnpwTVrhNPF3azgd6c6GDMp6X4w=="
        - "name": "DocDbEndpointUri"
          "value": "https://ridesharedev.documents.azure.com:443/"
        - "name": "DocDbRideShareDatabaseName"
          "value": "RideShare"
        - "name": "DocDbRideShareMainCollectionName"
          "value": "Main"
        - "name": "DocDbThroughput"
          "value": "400"
        - "name": "InsightsInstrumentationKey"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "IsRunningInContainer"
          "value": "true"
        - "name": "IsPersistDirectly"
          "value": "true"
        - "name": "AuthorityUrl"
          "value": "https://login.microsoftonline.com/tfp/relecloudrideshare.onmicrosoft.com/b2c_1_default-signin/v2.0"
        - "name": "ApiApplicationId"
          "value": "8df6f6dc-01f9-49d0-a49e-f23e29e71af5"
        - "name": "ApiScopeName"
          "value": "rideshare"
        - "name": "EnableAuth"
          "value": "false"
---
apiVersion: v1
kind: Service
metadata:
  name: rideshare-drivers
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rideshare-drivers
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rideshare-passengers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rideshare-passengers
    spec:
      containers:
      - name: rideshare-passengers
        image: khaledhikmat/rideshare-passengers:v1
        ports:
        - containerPort: 80
        env:
        - "name": "APPINSIGHTS_INSTRUMENTATIONKEY"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "FUNCTIONS_EXTENSION_VERSION"
          "value": "2.0.11961-alpha"
        - "name": "AzureWebJobsDashboard"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "AzureWebJobsStorage"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "DocDbApiKey"
          "value": "QGwfwS1QQDgfmiE7PFwZoAZwtwdB3yzZT3A5LgeXe0Go4WRqYbnXurlcHbOUnpwTVrhNPF3azgd6c6GDMp6X4w=="
        - "name": "DocDbEndpointUri"
          "value": "https://ridesharedev.documents.azure.com:443/"
        - "name": "DocDbRideShareDatabaseName"
          "value": "RideShare"
        - "name": "DocDbRideShareMainCollectionName"
          "value": "Main"
        - "name": "DocDbThroughput"
          "value": "400"
        - "name": "InsightsInstrumentationKey"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "IsRunningInContainer"
          "value": "true"
        - "name": "IsPersistDirectly"
          "value": "true"
        - "name": "GraphTenantId"
          "value": "dbe40d58-4cfa-4c49-b269-36b58ff2a62b"
        - "name": "GraphClientSecret"
          "value": "E7Vqg7cyFNQZkS/4eugaRQOEQgXqnpB5bSCZheVwxM4="
        - "name": "AuthorityUrl"
          "value": "https://login.microsoftonline.com/tfp/relecloudrideshare.onmicrosoft.com/b2c_1_default-signin/v2.0"
        - "name": "ApiApplicationId"
          "value": "8df6f6dc-01f9-49d0-a49e-f23e29e71af5"
        - "name": "ApiScopeName"
          "value": "rideshare"
        - "name": "EnableAuth"
          "value": "false"
---
apiVersion: v1
kind: Service
metadata:
  name: rideshare-passengers
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rideshare-passengers
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rideshare-orchestrators
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rideshare-orchestrators
    spec:
      containers:
      - name: rideshare-orchestrators
        image: khaledhikmat/rideshare-orchestrators:v1
        ports:
        - containerPort: 80
        env:
        - "name": "APPINSIGHTS_INSTRUMENTATIONKEY"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "FUNCTIONS_EXTENSION_VERSION"
          "value": "2.0.11961-alpha"
        - "name": "AzureWebJobsDashboard"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "AzureWebJobsStorage"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "DocDbApiKey"
          "value": "QGwfwS1QQDgfmiE7PFwZoAZwtwdB3yzZT3A5LgeXe0Go4WRqYbnXurlcHbOUnpwTVrhNPF3azgd6c6GDMp6X4w=="
        - "name": "DocDbEndpointUri"
          "value": "https://ridesharedev.documents.azure.com:443/"
        - "name": "DocDbRideShareDatabaseName"
          "value": "RideShare"
        - "name": "DocDbRideShareMainCollectionName"
          "value": "Main"
        - "name": "DocDbThroughput"
          "value": "400"
        - "name": "DriversAcknowledgeMaxWaitPeriodInSeconds"
          "value": "120"
        - "name": "DriversLocationRadiusInMiles"
          "value": "15"
        - "name": "TripMonitorIntervalInSeconds"
          "value": "10"
        - "name": "TripMonitorMaxIterations"
          "value": "20"
        - "name": "InsightsInstrumentationKey"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "IsRunningInContainer"
          "value": "true"
        - "name": "IsPersistDirectly"
          "value": "true"
        - "name": "TripManagersQueue"
          "value": "trip-managers"
        - "name": "TripMonitorsQueue"
          "value": "trip-monitors"
        - "name": "TripDemosQueue"
          "value": "trip-demos"
        - "name": "TripExternalizationsEventGridTopicUrl"
          "value": "https://ridesharetripexternalizationsdev.eastus-1.eventgrid.azure.net/api/events"
        - "name": "TripExternalizationsEventGridTopicApiKey"
          "value": "8fM+W112h6rxNvLtxL/yZAGA4KgfiSjQqsct+HeKjTY="
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rideshare-trips
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rideshare-trips
    spec:
      containers:
      - name: rideshare-trips
        image: khaledhikmat/rideshare-trips:v1
        ports:
        - containerPort: 80
        env:
        - "name": "APPINSIGHTS_INSTRUMENTATIONKEY"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "FUNCTIONS_EXTENSION_VERSION"
          "value": "2.0.11961-alpha"
        - "name": "AzureWebJobsDashboard"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "AzureWebJobsStorage"
          "value": "DefaultEndpointsProtocol=https;AccountName=ridesharefunctiondev;AccountKey=+tWw6Plk3PdDQNHFlfeZ4XiEy5OFSaJxw1lz79g/KOFUm0aMW9KS+hXePKN/gYRXrs3sZ7v3N2ngdvRACFfUZg=="
        - "name": "DocDbApiKey"
          "value": "QGwfwS1QQDgfmiE7PFwZoAZwtwdB3yzZT3A5LgeXe0Go4WRqYbnXurlcHbOUnpwTVrhNPF3azgd6c6GDMp6X4w=="
        - "name": "DocDbEndpointUri"
          "value": "https://ridesharedev.documents.azure.com:443/"
        - "name": "DocDbRideShareDatabaseName"
          "value": "RideShare"
        - "name": "DocDbRideShareMainCollectionName"
          "value": "Main"
        - "name": "DocDbThroughput"
          "value": "400"
        - "name": "SqlConnectionString"
          "value": "tcp:rideshare-db-dev.database.windows.net,1433;Initial Catalog=RideShare;Persist Security Info=False;User ID=rideshareadm!n;Password=rideShareS3cureP@ssword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - "name": "AzureSignalRConnectionString"
          "value": "https://rideshare-dev.service.signalr.net;AccessKey=p0A2YxgcBRul1/WvDqkhjmEnTThpbsLoiz3z7FiYjv4=;"
        - "name": "InsightsInstrumentationKey"
          "value": "546fbb26-8554-48fb-b370-12c8c5933541"
        - "name": "IsRunningInContainer"
          "value": "true"
        - "name": "IsEnqueueToOrchestrators"
          "value": "true"
        - "name": "IsPersistDirectly"
          "value": "true"
        - "name": "TripManagersQueue"
          "value": "trip-managers"
        - "name": "TripMonitorsQueue"
          "value": "trip-monitors"
        - "name": "TripDemosQueue"
          "value": "trip-demos"
        - "name": "AuthorityUrl"
          "value": "https://login.microsoftonline.com/tfp/relecloudrideshare.onmicrosoft.com/b2c_1_default-signin/v2.0"
        - "name": "ApiApplicationId"
          "value": "8df6f6dc-01f9-49d0-a49e-f23e29e71af5"
        - "name": "ApiScopeName"
          "value": "rideshare"
        - "name": "EnableAuth"
          "value": "false"
---
apiVersion: v1
kind: Service
metadata:
  name: rideshare-trips
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rideshare-trips
